### ISSUE TITLE
TODO List for WebRTC

### ISSUE THREAD

**Issue by ibsusu** [ibsusu/libtorrent#1]
- [ x ] Set up Opentracker, just use https://www.npmjs.com/package/bittorrent-tracker for starters, eh?
  - [ x ] Research how trackers keep track of peers
    - Users are kept track of by port, ip and peer id in ot_http.c then with macros in trackerlogic.h 
- [ ] Set up Coturn ICE server
  - [ ] Research/debug each step in ice process with coturn
- [ ] Set up Signalling Server https://www.npmjs.com/package/bittorrent-tracker for starters, gets complicated if separate signalling server is used.  redis for storage?  extra resources used?  Not worth it.  Ocelot and Opentracker need to be updated with ws and signalling support
  - [ ] Set up websocket server
- [ ] Set up peerid storage
- [ ] Set up webtorrent
  - [ ] Connect to Opentracker
  - [ ] Connect to Coturn 
  - [ ] Connect to Signaling Server
  - [ ] Find peers in DHT with magnet link- hard one, dunno how yet.
- [ ] libtorrent client
  - [ ] Connect to Opentracker
  - [ ] Connect to Signaling Server
    - [ ] Set up ws
    - [ ] Set up rawrtc
  - [ ] Connect to Coturn
- [ ] Transfer files between webtorrent and libtorrent client with tracker
- [ ] Set up libtorrent tests
- [ ] Create tests for webRTC
